// <auto-generated />
using System;
using Contacten.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Contacten.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250214132317_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Contacten.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Geboortedatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gemeente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacten");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Adres = "Somersstraat 22",
                            Email = "jesse.james@vdab.be",
                            Geboortedatum = new DateTime(1966, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gemeente = "Antwerpen",
                            Naam = "James",
                            Postcode = "2018",
                            Telefoon = "032021711",
                            Voornaam = "Jesse"
                        },
                        new
                        {
                            ContactId = 2,
                            Adres = "Interleuvenlaan 2",
                            Email = "jane.calamity@vdab.be",
                            Geboortedatum = new DateTime(1967, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gemeente = "Heverlee",
                            Naam = "Calamity",
                            Postcode = "3001",
                            Telefoon = "016380000",
                            Voornaam = "Jane"
                        },
                        new
                        {
                            ContactId = 3,
                            Adres = "Vlamingstraat 10",
                            Email = "billy.thekid@vdab.be",
                            Geboortedatum = new DateTime(1968, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gemeente = "Wevelgem",
                            Naam = "The Kid",
                            Postcode = "8560",
                            Telefoon = "056438080",
                            Voornaam = "Billy"
                        },
                        new
                        {
                            ContactId = 4,
                            Adres = "Industrieweg 50",
                            Email = "sarah.bernhardt@vdab.be",
                            Geboortedatum = new DateTime(1969, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Gemeente = "Wondelgem",
                            Naam = "Bernhardt",
                            Postcode = "9032",
                            Telefoon = "092541111",
                            Voornaam = "Sarah"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
